### PR TITLE
build in docker

### PR DESCRIPTION
**Pull request by pyaillet**
Hi !

Thanks for this project :)

Would you be interested in a docker container build ? 

I struggled a bit to setup a proper build env for this project so I tried to use the Docker image provided in this https://github.com/espressif/rust-esp32-example project and add the specific parts to it. It worked perfectly :)

### CODE REVIEW

**Comment by ivmarkov** [comment]
I'm a bit at a loss what exactly these Dockerfiles in your pull request are doing. Perhaps it is my ignorance of the dockerized Rust build (haven't tested it yet), but I was under the assumption, that you need just one docker "something" - and it is *the Rust ESP compiler fork itself*. Once you have it, you can use it to build crates that need the Rust ESP compiler fork, but that does *not* mean, that you need to dockerize these crates themselves?

If you can explain it to me, that would be great!

**Comment by pyaillet** [comment]
When I launch a `cargo build` in the docker container without installing `cargo-pio` I get this error at the end of the build:

```sh
error: linker `cargo-pio-link` not found
  |
  = note: No such file or directory (os error 2)
```

I saw that you put `cargo-pio` in the build-dependencies, but it does not seem to make it available during the build, so I chose the easiest way (to my knowledge) to make it available. Maybe there is a better way to do this ?

**Comment by ivmarkov** [comment]
> When I launch a `cargo build` in the docker container without installing `cargo-pio` I get this error at the end of the build:
> 
> ```shell
> error: linker `cargo-pio-link` not found
>   |
>   = note: No such file or directory (os error 2)
> ```
> 
> I saw that you put `cargo-pio` in the build-dependencies, but it does not seem to make it available during the build, so I chose the easiest way (to my knowledge) to make it available. Maybe there is a better way to do this ?

`cargo-pio` is simultaneously a library crate (and is therefore consumed as a build dependency), as well as two `cargo` subcommands:
* `cargo pio`
* `cargo pio-link`

We (still) do need the latter during the linking process - the situation might change with the recent upstreaming of some of the ESP-IDF support into the Rust libc crate. However the best way to support this is to ask Espressif to pre-install the `cargo-pio` subcommand inside the docker image. I'll talk to @georgik about that.

**Comment by pyaillet** [comment]
This would be a better solution :)

So I think this PR can be closed.

**Comment by georgik** [comment]
Hi @pyaillet . Thank you for the idea and the code. The solution in this repo is so-called cargo-first approach while espressif/rust-esp32-example is idf.py-first approach. The difference between solutions is in the name of command which invokes build.

Meanwhile we published updated image directly under espressif/idf-rust (`docker pull espressif/idf-rust`), so you do not need to refer my old image georgikrocks/idf-rust.

IMHO it might make sense to add this cargo-first approach to the image to have the check whether newer versions of compiler is working.

**Comment by pyaillet** [comment]
So I could open a PR on [this Dockerfile](https://github.com/espressif/rust-esp32-example/blob/main/Dockerfile) to add the `cargo-pio` crate installation to the build steps ?

**Comment by georgik** [comment]
@pyaillet It's not necessary, I can see the suggested changed in this PR. We will run some additional tests and we will update the Dockerfile.

**Comment by pyaillet** [comment]
Thank you :)

**Comment by georgik** [comment]
@pyaillet Please review suggested change in https://github.com/espressif/rust-esp32-example/pull/22

**Comment by georgik** [comment]
@pyaillet Your suggestion was included in new docker image with examples which uses as base image espressif/idf-rust.
Simply run:
```
docker run -it espressif/idf-rust-examples
```

**Comment by pyaillet** [comment]
It works perfectly, thanks :)

**Pull request closed without merging**
